name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake with Ninja
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=20

      - name: Build project
        run: cmake --build build
