name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          ninja --version

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Set up CMake
        run: |
          sudo apt-get install cmake
          cmake --version

      - name: Configure CMake with Clang
        run: |
          sudo apt-get install clang-15
          export CXX=clang++-15
          cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=20

      - name: Build project
        run: cmake --build build
