name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: 3.26

      - name: Configure CMake with Ninja
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=20

      - name: Build project
        run: cmake --build build

      - name: Run ctest
        run: |
          cd build
          ctest