name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run ctest
        run: |
          echo $GITHUB_WORKSPACE
          ls -al $GITHUB_WORKSPACE
          ls -al $GITHUB_WORKSPACE/build_artifact
          mv $GITHUB_WORKSPACE/build_artifact $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build
          ctest
