name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Output variables
        run: |
          echo $GITHUB_WORKSPACE
          echo ${{ github.workspace }}

      - name: Restore build artifacts
        run: mv $GITHUB_WORKSPACE/build-artifacts $GITHUB_WORKSPACE/build

      - name: Run ctest
        run: |
          cd $GITHUB_WORKSPACE/build
          ctest
