name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug workspace
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Contents of the workspace:"
          ls -al $GITHUB_WORKSPACE

      - name: Run ctest
        run: |
          cd $GITHUB_WORKSPACE/build
          ctest
